#Cascading layer 
cascading_ip:

OS_TENANT_NAME:

OS_USERNAME:

OS_PASSWORD: 123

OS_AUTH_URL:

#CNA info
cna_ssh_key:

cna_passwd:

#white list
white_list:
    - 127.0.0.1
    - 192.168.2.2