#Cascading layer 
cascading_ip:

OS_TENANT_NAME:

OS_USERNAME:

OS_PASSWORD: 123

OS_AUTH_URL:

#CNA info
cna_ssh_key:

cna_passwd:

#white list
white_list:
    - 127.0.0.1
    - 192.168.2.2

delay_threshold: 10

lossRate_threshold: 20

probe_interval: 60

pkg_count: 5

ipList:
    - 8.15.1.103
    - 8.15.1.105
    - 8.15.1.107
    - 8.10.23.110