probe_period: 60

port_count: 5

report_period: 120

pkg_count: 0

delay_threshold: 10

lossRate_threshold: 20

dscp: 0

lossPkg_timeout: 1

ak: 7e5oCeNRiHGu6FaGPQLDSQmPXu0a

sk: 8X2FBUVEiQWtsKGHI2fXCoT8kXUa

basicToken: N2U1b0NlTlJpSEd1NkZhR1BRTERTUW1QWHUwYTo4WDJGQlVWRWlRV3RzS0dISTJmWENvVDhrWFVh

repo_url: 8.15.4.10

eulerRepoUrl: http://8.15.4.10/dfs/download/root/ServerAntAgentForEuler.tar.gz

suseRepoUrl: http://8.15.4.10/dfs/download/root/ServerAntAgentForSles.tar.gz

installScriptRepoUrl: http://8.15.4.10/dfs/download/root/install_pntl.sh

agentConfUrl:

kafka_ip: 8.15.4.108:8000
topic: pntl
dropPkgThresh: 2