probe_period: 60

port_count: 5

report_period: 120

pkg_count: 0

delay_threshold: 10

lossRate_threshold: 20

dscp: 0

lossPkg_timeout: 1

ak: 0j_xmyclMrfvSzmMrGFdRbTLfYIa

sk: gTSMfZWx5bo3xILy754tItTp6Mca

basicToken: MGpfeG15Y2xNcmZ2U3ptTXJHRmRSYlRMZllJYTpnVFNNZlpXeDVibzN4SUx5NzU0dEl0VHA2TWNh